services:

  market-data:
    image: ${DOCKERHUB_USERNAME:-navlipi}/stockfolio-market-data:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile.market_data
    container_name: stockfolio-market-data
    ports:
      - "7666:7666"

  wallet:
    image: ${DOCKERHUB_USERNAME:-navlipi}/stockfolio-wallet:latest
    build:
      context: ./WalletMicroservice
      dockerfile: Dockerfile
    container_name: stockfolio-wallet
    ports:
      - "8091:8091"

  about:
    image: ${DOCKERHUB_USERNAME:-navlipi}/stockfolio-about:latest
    build:
      context: ./AboutMicroservice
      dockerfile: Dockerfile
    container_name: stockfolio-about
    ports:
      - "8090:8090"

  backend:
    image: ${DOCKERHUB_USERNAME:-navlipi}/stockfolio-backend:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: stockfolio-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      WALLET_SERVICE_URL: http://wallet:8091
      MARKET_DATA_BASE_URL: http://market-data:7666
      JWT_SECRET: thisisatncproject
    ports:
      - "8080:8080"
    depends_on:
      wallet:
        condition: service_started
      market-data:
        condition: service_started

  frontend:
    image: ${DOCKERHUB_USERNAME:-navlipi}/stockfolio-frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: stockfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - about
      - wallet
