spring:
  application:
    name: portfolio

  datasource:
    url: jdbc:h2:mem:portfolio_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

server:
  port: 8080

jwt:
  secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMjAyNFNlY3VyZUtleQ==
  expiration: 86400000